const fs = require('fs');

const arTranslations = {
  "Home": "الرئيسية",
  "Deals": "العروض",
  "Active Group Buys": "مجموعات الشراء النشطة",
  "Track every group you've joined or started.": "تتبع كل المجموعات التي انضممت إليها أو بدأتها.",
  "My Deals Overview": "نظرة عامة على عروضي",
  "Your Group Buying Power": "قوة الشراء الجماعي الخاصة بك",
  "The more you team up, the more you save.": "كلما كونت فريقاً، كلما وفرت أكثر.",
  "Create New Group": "إنشاء مجموعة جديدة",
  "Start a new group and unlock up to 15% off when you shop together.": "ابدأ مجموعة جديدة وافتح خصماً يصل إلى 15% عند التسوق معاً.",
  "Join Existing Group": "الانضمام لمجموعة قائمة",
  "Enter a group code from your friend to join their group.": "أدخل رمز المجموعة من صديقك للانضمام.",
  "Enter Group Code (e.g., GB-X72A)": "أدخل رمز المجموعة (مثال: GB-X72A)",
  "Join Now": "انضم الآن",
  "All Groups": "كل المجموعات",
  "Active": "نشط",
  "Expired": "منتهي",
  "Pending": "قيد الانتظار",
  "Members": "أعضاء",
  "Discount Unlocked": "تم تفعيل الخصم",
  "Ends on": "ينتهي في",
  "Ended on": "انتهى في",
  "Sort by: Recent": "الترتيب: الأحدث",
  "No groups found in this category.": "لم يتم العثور على مجموعات.",
  "2 Days Left": "يومان متبقيان",
  "4 Days Left": "4 أيام متبقية",
  "Sort by": "الترتيب حسب",
  "Most Popular": "الأكثر شيوعاً",
  "Price: Low to High": "السعر: من الأقل للأعلى",
  "Price: High to Low": "السعر: من الأعلى للأقل",
  "Wallet": "المحفظة",
  "Search products": "البحث عن منتجات",
  "Language": "اللغة",
  "Account": "الحساب",
  "Welcome to BuySAWA": "مرحباً بك في BuySAWA",
  "Contact Us": "تواصل معنا",
  "Help Center / FAQs": "مركز المساعدة / الأسئلة الشائعة",
  "About BuySAWA": "عن BuySAWA",
  "Privacy Policy": "سياسة الخصوصية",
  "Terms & Conditions": "الشروط والأحكام",
  "My Profile": "ملفي الشخصي",
  "My Orders": "طلباتي",
  "My Groups": "مجموعاتي",
  "Wishlist": "المفضلة",
  "Settings": "الإعدادات",
  "Logout": "تسجيل الخروج",
  "Back": "رجوع",
  "Loading products...": "جاري تحميل المنتجات..."
};

fs.writeFileSync('public/locales/ar/translation.json', JSON.stringify(arTranslations, null, 2), 'utf8');
console.log('Arabic translation file overwritten successfully!');
